package utill;

public enum Problem {
    NOT_ENOUGH_ELEMENTS, TOO_MANY_ELEMENTS, OUT_OF_RANGE_ID, NOT_IN_ALPHABET, NO_CONFIGURATION,
    FILE_NOT_FOUND, JAXB_ERROR , FILE_NOT_IN_FORMAT, ODD_ALPHABET_AMOUNT, NOT_ENOUGH_ROTORS, ROTORS_COUNT_BELOW_TWO,
    SELF_PLUGGING, ALREADY_PLUGGED, OUT_OF_RANGE_NOTCH, NUM_OF_REFLECTS_IS_NOT_HALF_OF_ABC , UNKNOWN, NO_PROBLEM,
    REFLECTOR_INVALID_ID_RANGE, REFLECTOR_SELF_MAPPING, REFLECTOR_ID_DUPLICATIONS, TOO_MANY_REFLECTORS, REFLECTOR_OUT_OF_RANGE_ID,
    ROTOR_MAPPING_NOT_IN_ALPHABET, ROTOR_MAPPING_NOT_A_LETTER, ROTOR_INVALID_ID_RANGE;
}
