package utill;

public enum Problem {
    NOT_ENOUGH_ELEMENTS, TOO_MANY_ELEMENTS, OUT_OF_RANGE_ID, NOT_IN_ALPHABET, NO_CONFIGURATION,
    FILE_NOT_FOUND, JAXB_ERROR , FILE_NOT_IN_FORMAT, ODD_ALPHABET_AMOUNT, NOT_ENOUGH_ROTORS, ROTORS_COUNT_BELOW_TWO,
    SELF_PLUGGING, ALREADY_PLUGGED, UNKNOWN, NO_PROBLEM;
}
