public interface EnigmaAPI {
    public enum Instructions {
        READ_SYSTEM_DETAILS, DISPLAY_SPECS, CHOOSE_INIT_CONFIG_MANUAL,
        CHOOSE_INIT_CONFIG_AUTO, PROCESS_INPUT, RESET_CURRENT_CODE,
        HISTORY_AND_STATISTICS, EXIT_SYSTEM
    }
}
